import enum 

class EventType(enum.Enum):
    NETWORK_CONNECTED = 1
    NETWORK_DISCONNECTED = 2
    NETWORK_RECONNECTING = 3 

    READY = 4
    HELLO = 5
    DISPATCH = 6
    HEARTBEAT = 7
    HEARTBEAT_ACK = 8

    GUILD_CREATE = 9
    GUILD_DELETE = 10
    GUILD_UPDATE = 11
    GUILD_POSITION = 12

    CHANNEL_CREATE = 13
    CHANNEL_DELETE = 14
    CHANNEL_UPDATE = 15
    CHANNEL_POSITION = 16

    GUILD_ROLE_CREATE = 17
    GUILD_ROLE_DELETE = 18
    GUILD_ROLE_UPDATE = 19
    GUILD_ROLE_POSITION = 20

    GUILD_MEMBER_ADD = 21
    GUILD_MEMBER_REMOVE = 22
    GUILD_MEMBER_UPDATE = 23

    EMOJI_CREATE = 24
    EMOJI_DELETE = 25
    EMOJI_UPDATE = 26

    MESSAGE_CREATE = 27
    MESSAGE_DELETE = 28
    MESSAGE_UPDATE = 29

    MESSAGE_REACTION_ADD = 30
    MESSAGE_REACTION_REMOVE = 31

    USER_TYPING = 32
    USER_PRESENCE_UPDATE = 33

    VOICE_STATE_UPDATE = 34
